language: node_js
os: osx
node_js: "6"
matrix:
  include:
    - osx_image: xcode9
    - osx_image: xcode9.4
    - osx_image: xcode10
    - osx_image: xcode10.1
    - osx_image: xcode10.2
cache:
  directories:
    - node_modules
before_install:
  - "git config protocol.version; true"

  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"

  # Remove all non-test dependencies
  - "npm rm --save-dev connect-redis"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm run test-ci"
  - "npm run lint"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"

notifications:
  email: false
